# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170503_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this profile should be treated as active. ', verbose_name='is active'),
        ),
    ]
