# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.Manager', verbose_name='Manager'),
            preserve_default=False,
        ),
    ]
